# Generated by Django 5.0.1 on 2024-01-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='comision',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
